### PR TITLE
Feature/api

### PR DESCRIPTION
**Pull request by AmineDerbal**
in this milestone ♻️ 

- add workflow and setup linters 👍 
- fetch crypto coins Api 👍 
- display list of crypto coins 👍
- display a detail page for each crypto coin 👍 
- implement testing 👍 
- Highlight code in the presentation 👍 
- the app is deployed [here](https://643d6e77f0f1ad007d2a1498--idyllic-semifreddo-83ba58.netlify.app/)  👍 
- video presentation [here](https://screenrec.com/share/YVLkbnjBeJ)

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @coker2019 and Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>

</div>


You have submitted a project not having the given linters configuration for a react/redux project. Kindly ensure that the `eslintrc.json` file is [exactly as given](https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json).

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @AmineDerbal👋, 

### You are doing a marvelous job on the React capstone project and this is one of the best projects I have seen so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

image

## To Highlight 🎉
- Nice UI design. ✔️
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- All tests are passed. ✔️
- PR has a good title and summary. ✔️



## Required Changes ♻️

- [ ] Please make sure in the presentation video also to show some piece of code that you're proud of as requested in the project requirements. (You need to record the presentation video again).
- [ ] The issues page in the README file is broken, Please make sure to fix it. It will make the README file more professional.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AmineDerbal** [comment]
- fix the broken link for issues link 👍 
- made a new presentation video [here](https://screenrec.com/share/dl4csmS2Vn) 👍 
- the interesting piece code is highlighted from 02:22 👍

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @AmineDerbal,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

giphy (1)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
